version: "3.7"
services:
  graylog:
    image: docker.io/graylog/graylog:3.2
    environment:
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      GRAYLOG_PASSWORD_SECRET: hP8hqbG85evhEJil4bdkXdcTG0UrPy1YYpRESYru0HoSMFcWMaC2pxlabi2Uz6Mlb3jpFh7m0VRUlPjnED4KcluoSMclQLZD
      GRAYLOG_ROOT_PASSWORD_SHA2: 13d249f2cb4127b40cfa757866850278793f814ded3c587fe5889e889a7a9f6c
      GRAYLOG_MONGODB_URI: mongodb://mongo/graylog
    ports:
      - 9000:9000
  mongo:
    image: docker.io/mongo:latest
    ports:
      - 27017:27017
  elasticsearch:
    image: docker.io/elasticsearch:6.8.6
    environment:
      discovery.type: single-node
    ulimits:
      nofile: 65536
    ports:
      - 9200:9200
      - 9300:9300